# NumPy Arrays - Part 4<br>

by uramoon@kw.ac.kr<br>
원본 출처: Introduction to Deep Learning at Carnegie Mellon University (https://deeplearning.cs.cmu.edu/S22/index.html)

In [41]:
# Import the NumPy 
import numpy as np

## Reshaping Arrays (배열의 모양을 다르게 해석하기)<br>

Array reshaping은 배열안의 데이터는 그대로 두고 모양을 바꿔 해석을 다르게 하는 것입니다.

예를 들어 (4,) 모양의 1차원 배열 [1, 2, 3, 4]는 (4, 1) 모양의 2차원 배열 [[1], [2], [3], [4]], <br> 또는 (2, 2) 모양의 2차원 배열 [[1, 2], [3, 4]] 및 (1, 4) 모양의 2차원 배열 [[1, 2, 3, 4]]로 형태를 바꿔 해석할 수도 있습니다.

### 동일 차원으로 reshaping

In [42]:
s = np.random.rand(3, 4, 5)
print(f"원래 모양: {s.shape}")

원래 모양: (3, 4, 5)


***TODO: s의 전체 원소 개수 구하기***
* Q: 어떻게 계산할 수 있을까요?
* A: 3x4x5

In [43]:
s.size

60

In [44]:
# s 내용 확인하기
print(s)

[[[0.17999355 0.51121561 0.93234785 0.49361973 0.40843001]
  [0.51635041 0.83096943 0.88819646 0.64803026 0.72626995]
  [0.90300073 0.12806434 0.45606986 0.75344171 0.68342551]
  [0.61881172 0.65081256 0.59742903 0.23725997 0.35941103]]

 [[0.95657196 0.40672013 0.26140057 0.96571747 0.66341768]
  [0.51623449 0.99468697 0.73297764 0.33419532 0.4428833 ]
  [0.96605786 0.89174303 0.43889062 0.42984987 0.41095418]
  [0.36701972 0.81852886 0.58303167 0.44603061 0.70061311]]

 [[0.95558444 0.76076263 0.01883646 0.97794153 0.84530883]
  [0.84050618 0.96355429 0.2265942  0.90667866 0.70762831]
  [0.59359504 0.22984864 0.22749144 0.447599   0.49709902]
  [0.90610332 0.10752447 0.33163226 0.91148006 0.36911634]]]


In [45]:
# TODO: s를 (2, 6, 5)로 reshape하여 s1에 저장하기
s1 = s.reshape(2,6 ,5 )
print(f"s1의 모양: {s1.shape}")

s1의 모양: (2, 6, 5)


In [46]:
# s와 s1의 각 원소값과 위치는 동일한 것을 확인해보세요.
print(s1)

[[[0.17999355 0.51121561 0.93234785 0.49361973 0.40843001]
  [0.51635041 0.83096943 0.88819646 0.64803026 0.72626995]
  [0.90300073 0.12806434 0.45606986 0.75344171 0.68342551]
  [0.61881172 0.65081256 0.59742903 0.23725997 0.35941103]
  [0.95657196 0.40672013 0.26140057 0.96571747 0.66341768]
  [0.51623449 0.99468697 0.73297764 0.33419532 0.4428833 ]]

 [[0.96605786 0.89174303 0.43889062 0.42984987 0.41095418]
  [0.36701972 0.81852886 0.58303167 0.44603061 0.70061311]
  [0.95558444 0.76076263 0.01883646 0.97794153 0.84530883]
  [0.84050618 0.96355429 0.2265942  0.90667866 0.70762831]
  [0.59359504 0.22984864 0.22749144 0.447599   0.49709902]
  [0.90610332 0.10752447 0.33163226 0.91148006 0.36911634]]]


### 다른 차원으로 reshaping

In [47]:
# TODO: 0부터 119까지 120개의 정수로 이루어진 1차원 배열을 간단하게 만들어보세요.
r = np.arange(0,120)

In [48]:
print(f"원래 모양: {r.shape}")

원래 모양: (120,)


In [49]:
# TODO: (120,) -> (3, 4, 10)
# 원소개수는 120개로 동일합니다.
r1 = r.reshape(3,4,10)
print(f"r1의 모양: {r1.shape}")

r1의 모양: (3, 4, 10)


In [50]:
# r과 r1을 비교해보세요.
print(r)
print(r1)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 1

In [51]:
# TODO: r1을 reshape하여 r2에 저장하세요.
# (3, 4, 10) -> (6, 20)
r2 = r1.reshape(6,20)
print(f"r2의 모양: {r2.shape}")

r2의 모양: (6, 20)


In [52]:
# r2와 r1, r을 비교해보세요.
print(r1)
print(r2)

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]]]
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109

## 배열 펼치기 (Flattening)
배열 펼치기는 다차원 배열을 일차원으로 만들어줍니다.<br>
일반적인 다층 퍼셉트론 인공 신경망은 일차원 배열을 입력으로 받기 때문에<br> MNIST 데이터셋을 사용하면 28 x 28 모양의 이차원 배열을 길이 784의 일차원 배열로 만들어 사용합니다.

In [53]:
k = np.random.rand(5, 6)
k

array([[0.70513431, 0.14356709, 0.28945293, 0.61497921, 0.42376015,
        0.00314452],
       [0.36760621, 0.76038113, 0.52135353, 0.06441742, 0.77714865,
        0.12138275],
       [0.19489493, 0.72290735, 0.20955088, 0.23762168, 0.20583207,
        0.42492134],
       [0.17902291, 0.35507158, 0.01207323, 0.57231921, 0.43901214,
        0.20368527],
       [0.56150639, 0.77753036, 0.0714515 , 0.44118067, 0.91569067,
        0.30389071]])

### 기본 순서대로 펼치기

In [54]:
# k와 k1을 비교해보세요.
k1 = k.flatten() 
k1

array([0.70513431, 0.14356709, 0.28945293, 0.61497921, 0.42376015,
       0.00314452, 0.36760621, 0.76038113, 0.52135353, 0.06441742,
       0.77714865, 0.12138275, 0.19489493, 0.72290735, 0.20955088,
       0.23762168, 0.20583207, 0.42492134, 0.17902291, 0.35507158,
       0.01207323, 0.57231921, 0.43901214, 0.20368527, 0.56150639,
       0.77753036, 0.0714515 , 0.44118067, 0.91569067, 0.30389071])

In [55]:
k1.shape

(30,)

## 배열 이어 붙이기
https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [56]:
# 2차원 배열인 array1과 array2 생성
array1 = np.array([[1, 2], [3, 4]])
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.array([[5, 6]])
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

Array 1 is 
 [[1 2]
 [3 4]]  with dimensions  (2, 2) 

Array 2 is 
 [[5 6]]  with dimensions  (1, 2) 



배열을 이어붙일 때에는 기준이 되는 축 이외에 모양이 동일해야 합니다.<br>
1. (2, 2)와 (1, 2) 이어 붙일 때 0번 축으로 이어붙이면 (3, 2) 배열 탄생
2. (2, 2)와 (1, 2) 이어 붙일 때 1번 축으로 이어붙이면 0번 축의 모양이 서로 다르므로 이어붙이기 실패

In [57]:
# TODO: 0번 축을 기준으로 array1과 array2를 이어붙이세요.
concatenated_array1 = np.concatenate((array1,array2),axis=0)
print("Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is \n", concatenated_array1, "with dimensions ", concatenated_array1.shape, '\n')

Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is 
 [[1 2]
 [3 4]
 [5 6]] with dimensions  (3, 2) 



In [59]:
# TODO: 1번 축을 기준으로 array1과 array2를 이어붙이세요. (실패합니다. 에러 메시지를 확인하세요.)
concatenated_array2 = np.concatenate((array1,array2),axis=1)
print("Concatenated array 2 along axis 0 (column-wise for 2-d arrays) is \n", concatenated_array2, "with dimensions ", concatenated_array2.shape)
#축의 개수가 다르기 때문에 나타나는 오류

ValueError: ignored

In [60]:
# TODO: (3, 4, 5) 형태에 0 이상 3 미만의 무작위 정수로 채워진 배열을 만드세요.
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html
array1 = np.array(np.random.randint(0,3,(3,4,5)))
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

Array 1 is 
 [[[2 1 0 0 1]
  [1 1 2 2 2]
  [1 0 1 2 0]
  [0 0 0 1 0]]

 [[2 0 2 2 0]
  [2 1 0 1 2]
  [0 0 0 2 0]
  [2 2 2 1 1]]

 [[1 2 2 2 1]
  [2 2 0 2 2]
  [1 1 0 1 0]
  [1 2 0 0 2]]]  with dimensions  (3, 4, 5) 



In [61]:
# TODO: (3, 4, 5) 형태에 0 이상 4 미만의 무작위 정수로 채워진 배열을 만드세요.
array2 = np.array(np.random.randint(0,4,(3,4,5)))
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

Array 2 is 
 [[[0 3 3 3 3]
  [1 0 3 1 3]
  [3 2 0 0 0]
  [0 1 0 2 3]]

 [[1 3 3 2 0]
  [1 0 0 2 2]
  [3 1 2 0 1]
  [3 2 0 3 2]]

 [[3 1 0 2 2]
  [3 3 1 3 3]
  [2 1 0 3 3]
  [1 0 2 0 0]]]  with dimensions  (3, 4, 5) 



***TODO: 0번 축을을 기준으로 이어붙이기***
* Q: 어떤 모양일까요? (코딩으로 결과 확인 전에 작성해보세요.)
* A: (6,4,5)

In [62]:
# TODO: 0번 축을 기준으로 이어붙이기
concatenated_array1 = np.concatenate((array1,array2),axis=0)
print("Concatenated array 1 is \n", concatenated_array1, "\n\n", "and the dimensions of the concatenated array 1 are: \n", concatenated_array1.shape)

Concatenated array 1 is 
 [[[2 1 0 0 1]
  [1 1 2 2 2]
  [1 0 1 2 0]
  [0 0 0 1 0]]

 [[2 0 2 2 0]
  [2 1 0 1 2]
  [0 0 0 2 0]
  [2 2 2 1 1]]

 [[1 2 2 2 1]
  [2 2 0 2 2]
  [1 1 0 1 0]
  [1 2 0 0 2]]

 [[0 3 3 3 3]
  [1 0 3 1 3]
  [3 2 0 0 0]
  [0 1 0 2 3]]

 [[1 3 3 2 0]
  [1 0 0 2 2]
  [3 1 2 0 1]
  [3 2 0 3 2]]

 [[3 1 0 2 2]
  [3 3 1 3 3]
  [2 1 0 3 3]
  [1 0 2 0 0]]] 

 and the dimensions of the concatenated array 1 are: 
 (6, 4, 5)


***TODO: 1번 축을 기준으로 이어붙이기***
* Q: 어떤 모양일까요? (코딩으로 결과 확인 전에 작성해보세요.)
* A: (3,8,5)

In [63]:
# TODO: 1번 축을 기준으로 이어붙이기
concatenated_array2 = np.concatenate((array1,array2),axis=1)
print("Concatenated array 2 is \n", concatenated_array2, "\n\n", "and the dimensions of the concatenated array 2 are: \n", concatenated_array2.shape)

Concatenated array 2 is 
 [[[2 1 0 0 1]
  [1 1 2 2 2]
  [1 0 1 2 0]
  [0 0 0 1 0]
  [0 3 3 3 3]
  [1 0 3 1 3]
  [3 2 0 0 0]
  [0 1 0 2 3]]

 [[2 0 2 2 0]
  [2 1 0 1 2]
  [0 0 0 2 0]
  [2 2 2 1 1]
  [1 3 3 2 0]
  [1 0 0 2 2]
  [3 1 2 0 1]
  [3 2 0 3 2]]

 [[1 2 2 2 1]
  [2 2 0 2 2]
  [1 1 0 1 0]
  [1 2 0 0 2]
  [3 1 0 2 2]
  [3 3 1 3 3]
  [2 1 0 3 3]
  [1 0 2 0 0]]] 

 and the dimensions of the concatenated array 2 are: 
 (3, 8, 5)


***TODO: 2번 축을 기준으로 이어붙이기***
* Q: 어떤 모양일까요? (코딩으로 결과 확인 전에 작성해보세요.)
* A: (3,4,10)

In [64]:
# TODO: 2번 축을 기준으로 이어붙이기
concatenated_array3 = np.concatenate((array1,array2),axis=2)
print("Concatenated array 3 is \n", concatenated_array3, "\n\n", "and the dimensions of the concatenated array 3 are: \n", concatenated_array3.shape)

Concatenated array 3 is 
 [[[2 1 0 0 1 0 3 3 3 3]
  [1 1 2 2 2 1 0 3 1 3]
  [1 0 1 2 0 3 2 0 0 0]
  [0 0 0 1 0 0 1 0 2 3]]

 [[2 0 2 2 0 1 3 3 2 0]
  [2 1 0 1 2 1 0 0 2 2]
  [0 0 0 2 0 3 1 2 0 1]
  [2 2 2 1 1 3 2 0 3 2]]

 [[1 2 2 2 1 3 1 0 2 2]
  [2 2 0 2 2 3 3 1 3 3]
  [1 1 0 1 0 2 1 0 3 3]
  [1 2 0 0 2 1 0 2 0 0]]] 

 and the dimensions of the concatenated array 3 are: 
 (3, 4, 10)
