# NumPy Arrays - Part 3<br>
NumPy - 대규모의 다차원 배열을 쉽게 처리할 때 사용하는 파이썬 라이브러리<br>

원본 출처: Introduction to Deep Learning at Carnegie Mellon University (https://deeplearning.cs.cmu.edu/S22/index.html)

In [17]:
# Import the NumPy 
import numpy as np

## 1. 데이터 읽어오기

### a. 인덱싱: NumPy 배열에서 값 읽어오기

In [18]:
# TODO: 무작위 값으로 채워진 4 x 5 x 6 배열을 만들어보세요. (5 x 6 행렬이 4개 묶음 있는 것으로 해석할 수 있음)
n = np.random.rand(4, 5, 6)
n.shape

(4, 5, 6)

나중에 다룰 MNIST (필기체 인식) 데이터셋의 모양은 (60000, 28, 28)인데
28 (행의 수, 높이) x 28 (열의 수, 너비)의 그림 60000만장이 있는 것으로 해석됩니다.

In [19]:
# TODO: n에서 두 번째 묶음의 세 번째 행, 네 번째 열의 값은? (인덱스는 0에서 시작함)

n[1][2][3]

0.14613014307393513

### b. 슬라이싱: NumPy 배열의 일부를 가져오기

시작(포함):끝(미포함)으로 연속된 항목을 슬라이싱 <br>
:만 쓰면 전체

In [20]:
# 첫 번째 묶음의 모든 행렬 가져오기
print(n[0, :, :]) # same as: n[0], 정답이므로 수정할 필요 없음

[[0.17499086 0.79057158 0.70392876 0.20966316 0.90944325 0.9666683 ]
 [0.65384716 0.15666819 0.58407713 0.03410145 0.53366472 0.20820603]
 [0.1399377  0.4011908  0.09422645 0.91397611 0.47171973 0.82911504]
 [0.43661816 0.91651681 0.4313007  0.29186    0.09081065 0.50342498]
 [0.84241931 0.29319996 0.22771251 0.10204733 0.12395176 0.02964839]]


In [21]:
# TODO: 첫 번째 묶음에서 [0, 3) 행, [0, 4) 열 가져오기, 즉 3 x 4 배열이 나와야 함
print(n[0,:3 ,:4 ])

[[0.17499086 0.79057158 0.70392876 0.20966316]
 [0.65384716 0.15666819 0.58407713 0.03410145]
 [0.1399377  0.4011908  0.09422645 0.91397611]]


In [22]:
# TODO: 전체 묶음에서 4번 째 행, 5번째 열 값들 가져오기
print(n[:,3:4 , 4:5]) 

[[[0.09081065]]

 [[0.13811195]]

 [[0.36606787]]

 [[0.50113561]]]


### c. Slicing at Interval
시작::증가폭(스텝)으로 띄엄띄엄 슬라이싱<br>
예) a[7::2]인 경우 a[7], a[9], a[11], ... 을 가져와서 배열로 만듦

In [23]:
# TODO: 0번 묶음, 2번 묶음, 4번 묶음, ... 슬라이싱 (n은 3번 묶음까지만 있어서 두 개의 묶음만 출력됨)
print(n[0::2]) 

[[[0.17499086 0.79057158 0.70392876 0.20966316 0.90944325 0.9666683 ]
  [0.65384716 0.15666819 0.58407713 0.03410145 0.53366472 0.20820603]
  [0.1399377  0.4011908  0.09422645 0.91397611 0.47171973 0.82911504]
  [0.43661816 0.91651681 0.4313007  0.29186    0.09081065 0.50342498]
  [0.84241931 0.29319996 0.22771251 0.10204733 0.12395176 0.02964839]]

 [[0.99719152 0.53264257 0.17841442 0.85741047 0.88288598 0.36887377]
  [0.31747379 0.56922666 0.38921576 0.85805521 0.17920737 0.73026188]
  [0.49266143 0.51396386 0.25710882 0.67981646 0.58109345 0.12109302]
  [0.1200661  0.31359511 0.34734078 0.00300424 0.36606787 0.11168611]
  [0.72117971 0.7954443  0.38479242 0.55890931 0.32227559 0.8112213 ]]]


원래 n의 모습과 비교해가며 아래의 결과는 어떻게 만들어진 것인지 이해하고 넘어가세요.

In [24]:
print(n[0::2, 1:4, 1::2]) 

[[[0.15666819 0.03410145 0.20820603]
  [0.4011908  0.91397611 0.82911504]
  [0.91651681 0.29186    0.50342498]]

 [[0.56922666 0.85805521 0.73026188]
  [0.51396386 0.67981646 0.12109302]
  [0.31359511 0.00300424 0.11168611]]]


## 2. 데이터 수정하기

In [25]:
# 배열 복사하기
n_copy = np.copy(n)

### a. 하나의 값 수정하기

In [26]:
# 복사한 배열과 n이 같은지 하나의 항목 확인
print(n_copy[2, 4, 1] == n[2, 4, 1])

True


In [27]:
# TODO: 복사한 배열 n_copy[2, 4, 1]의 값을 0.005로 변경
n_copy[2,4,1]=0.005

# 여전히 내용이 같은지 확인
print(n_copy[2, 4, 1] == n[2, 4, 1])

False


n_copy는 n을 복사한 것이지만 n과 다른 위치에 독립적으로 존재한다. 만약 copy 함수로 복사하지 않고 m = n으로 m을 만든다음 m[2, 4, 1] 값을 수정하면 어떻게 될까? 

In [28]:
print('Before: ', n[2, 4, 1])
m = n
m[2, 4, 1] = 0.5
print('After: ', n[2, 4, 1])

Before:  0.7954443017115326
After:  0.5


In [29]:
# n, m, n_copy가 저장된 장소 출력
print(id(n))
print(id(m))
print(id(n_copy))

140593607894000
140593607894000
140593118204720


### b. 여러 항목의 값을 같은 값으로 수정하기

In [30]:
n_copy = np.copy(n)

# n_copy 3번째 묶음의 4번째 행의 값 확인
print(n_copy[2, 3])

[0.1200661  0.31359511 0.34734078 0.00300424 0.36606787 0.11168611]


In [31]:
# TODO: n_copy 3번째 묶음, 4번째 행의 값을 모두 0.5로 바꾸기
n_copy[2, 3] = 0.5

# n_copy 3번째 묶음의 4번째 열의 값 확인
print(n_copy[2, 3])

[0.5 0.5 0.5 0.5 0.5 0.5]
